import numpy
import typing
from typing import Callable, ClassVar, overload

COUNT: OBPlaybackStatus
PAUSED: OBPlaybackStatus
PLAYING: OBPlaybackStatus
SAMPLE_RATE_100_HZ: OBGyroSampleRate
SAMPLE_RATE_12_5_HZ: OBGyroSampleRate
SAMPLE_RATE_16_KHZ: OBGyroSampleRate
SAMPLE_RATE_1_5625_HZ: OBGyroSampleRate
SAMPLE_RATE_1_KHZ: OBGyroSampleRate
SAMPLE_RATE_200_HZ: OBGyroSampleRate
SAMPLE_RATE_25_HZ: OBGyroSampleRate
SAMPLE_RATE_2_KHZ: OBGyroSampleRate
SAMPLE_RATE_32_KHZ: OBGyroSampleRate
SAMPLE_RATE_3_125_HZ: OBGyroSampleRate
SAMPLE_RATE_4_KHZ: OBGyroSampleRate
SAMPLE_RATE_500_HZ: OBGyroSampleRate
SAMPLE_RATE_50_HZ: OBGyroSampleRate
SAMPLE_RATE_6_25_HZ: OBGyroSampleRate
SAMPLE_RATE_8_KHZ: OBGyroSampleRate
STOPPED: OBPlaybackStatus
UNKNOWN: OBPlaybackStatus

class AccelFrame(Frame):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_temperature(self) -> float: ...
    def get_value(self) -> OBAccelValue: ...
    def get_x(self) -> float: ...
    def get_y(self) -> float: ...
    def get_z(self) -> float: ...

class AccelStreamProfile(StreamProfile):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_full_scale_range(self) -> OBAccelFullScaleRange: ...
    def get_intrinsic(self) -> OBAccelIntrinsic: ...
    def get_sample_rate(self) -> OBGyroSampleRate: ...

class AlignFilter(Filter):
    def __init__(self, align_to_stream: OBStreamType) -> None: ...
    def get_align_to_stream_type(self) -> OBStreamType: ...

class CameraParamList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_camera_param(self, arg0: int) -> OBCameraParam: ...
    def get_count(self) -> int: ...
    def __getitem__(self, arg0: int) -> OBCameraParam: ...
    def __iter__(self) -> typing.Iterator[OBCameraParam]: ...
    def __len__(self) -> int: ...

class ColorFrame(VideoFrame):
    def __init__(self, *args, **kwargs) -> None: ...

class ConfidenceFrame(VideoFrame):
    def __init__(self, *args, **kwargs) -> None: ...

class Config:
    def __init__(self) -> None: ...
    def disable_all_stream(self) -> None: ...
    @overload
    def disable_stream(self, arg0: OBStreamType) -> None: ...
    @overload
    def disable_stream(self, arg0: OBSensorType) -> None: ...
    def enable_accel_stream(self, full_scale_range: OBAccelFullScaleRange = ..., sample_rate: OBGyroSampleRate = ...) -> None: ...
    def enable_all_stream(self) -> None: ...
    def enable_gyro_stream(self, full_scale_range: OBGyroFullScaleRange = ..., sample_rate: OBGyroSampleRate = ...) -> None: ...
    def enable_lidar_stream(self, scan_rate: OBLiDARScanRate = ..., format: OBFormat = ...) -> None: ...
    @overload
    def enable_stream(self, arg0) -> None: ...
    @overload
    def enable_stream(self, arg0: OBStreamType) -> None: ...
    @overload
    def enable_stream(self, arg0: OBSensorType) -> None: ...
    @overload
    def enable_video_stream(self, stream_type: OBStreamType, width: int = ..., height: int = ..., fps: int = ..., format: OBFormat = ...) -> None: ...
    @overload
    def enable_video_stream(self, sensor_type: OBSensorType, width: int = ..., height: int = ..., fps: int = ..., format: OBFormat = ...) -> None: ...
    @overload
    def enable_video_stream(self, sensor_type: OBSensorType, decimation_config: OBHardwareDecimationConfig, fps: int = ..., format: OBFormat = ...) -> None: ...
    def get_enabled_stream_profile_list(self, *args, **kwargs): ...
    def set_align_mode(self, arg0: OBAlignMode) -> None: ...
    def set_depth_scale_require(self, arg0: bool) -> None: ...
    def set_frame_aggregate_output_mode(self, arg0: OBFrameAggregateOutputMode) -> None: ...

class Context:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    def create_net_device(self, *args, **kwargs): ...
    def enable_multi_device_sync(self, arg0: int) -> None: ...
    def enable_net_device_enumeration(self, arg0: bool) -> None: ...
    @staticmethod
    def log_external_message(arg0: OBLogLevel, arg1: str, arg2: str, arg3: str, arg4: str, arg5: int) -> None: ...
    def ob_force_ip_config(self, arg0: str, arg1: OBDeviceIpAddrConfig) -> bool: ...
    def query_devices(self, *args, **kwargs): ...
    def register_device_changed_callback(self, arg0: Callable) -> int: ...
    def set_device_changed_callback(self, arg0: Callable) -> None: ...
    @staticmethod
    def set_logger_file_name(arg0: str) -> None: ...
    @staticmethod
    def set_logger_level(arg0: OBLogLevel) -> None: ...
    @staticmethod
    def set_logger_to_callback(arg0: OBLogLevel, arg1: Callable) -> None: ...
    @staticmethod
    def set_logger_to_console(arg0: OBLogLevel) -> None: ...
    @staticmethod
    def set_logger_to_file(arg0: OBLogLevel, arg1: str) -> None: ...
    def unregister_device_changed_callback(self, arg0: int) -> None: ...

class DecimationFilter(Filter):
    def __init__(self) -> None: ...
    def get_scale_range(self) -> OBUint8PropertyRange: ...
    def get_scale_value(self) -> int: ...
    def set_scale_value(self, arg0: int) -> None: ...

class DepthFrame(VideoFrame):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_depth_scale(self) -> float: ...
    def set_value_scale(self, arg0: float) -> None: ...

class Device:
    def __init__(self, *args, **kwargs) -> None: ...
    def enable_heart_beat(self, arg0: bool) -> None: ...
    def export_settings_as_preset_json_file(self, arg0: str) -> None: ...
    def get_available_preset_list(self) -> DevicePresetList: ...
    def get_available_preset_resolution_config_list(self) -> PresetResolutionConfigList: ...
    def get_baseline(self) -> OBBaselineCalibrationParam: ...
    def get_bool_property(self, arg0: OBPropertyID) -> bool: ...
    def get_bool_property_range(self, arg0: OBPropertyID) -> OBBoolPropertyRange: ...
    def get_calibration_camera_param_list(self, *args, **kwargs): ...
    def get_current_preset_name(self) -> str: ...
    def get_depth_work_mode(self) -> OBDepthWorkMode: ...
    def get_depth_work_mode_list(self) -> OBDepthWorkModeList: ...
    def get_device_info(self) -> DeviceInfo: ...
    def get_device_state(self) -> int: ...
    def get_float_property(self, arg0: OBPropertyID) -> float: ...
    def get_float_property_range(self, arg0: OBPropertyID) -> OBFloatPropertyRange: ...
    def get_int_property(self, arg0: OBPropertyID) -> int: ...
    def get_int_property_range(self, arg0: OBPropertyID) -> OBIntPropertyRange: ...
    def get_multi_device_sync_config(self) -> OBMultiDeviceSyncConfig: ...
    def get_sensor(self, *args, **kwargs): ...
    def get_sensor_list(self, *args, **kwargs): ...
    def get_support_property_count(self) -> int: ...
    def get_supported_property(self, arg0: int) -> OBPropertyItem: ...
    def get_temperature(self) -> OBDeviceTemperature: ...
    def get_timestamp_reset_config(self) -> OBDeviceTimestampResetConfig: ...
    def isFrameInterleaveSupported(self) -> bool: ...
    def is_property_supported(self, arg0: OBPropertyID, arg1: OBPermissionType) -> bool: ...
    def loadFrameInterleave(self, arg0: str) -> None: ...
    def load_depth_filter_config(self, arg0: str) -> None: ...
    def load_preset(self, arg0: str) -> None: ...
    def load_preset_from_json_data(self, arg0: str, arg1: str) -> None: ...
    def load_preset_from_json_file(self, arg0: str) -> None: ...
    def reboot(self) -> None: ...
    def set_bool_property(self, arg0: OBPropertyID, arg1: bool) -> None: ...
    @overload
    def set_depth_work_mode(self, arg0: OBDepthWorkMode) -> OBStatus: ...
    @overload
    def set_depth_work_mode(self, arg0: str) -> OBStatus: ...
    def set_device_state_changed_callback(self, arg0: Callable) -> None: ...
    def set_float_property(self, arg0: OBPropertyID, arg1: float) -> None: ...
    def set_hdr_config(self, arg0: OBHdrConfig) -> None: ...
    def set_int_property(self, arg0: OBPropertyID, arg1: int) -> None: ...
    def set_ip_config(self, arg0: OBDeviceIpAddrConfig) -> None: ...
    def set_multi_device_sync_config(self, arg0: OBMultiDeviceSyncConfig) -> None: ...
    def set_preset_resolution_config(self, arg0: OBPresetResolutionConfig) -> None: ...
    def set_timestamp_reset_config(self, arg0: OBDeviceTimestampResetConfig) -> None: ...
    def timer_reset(self) -> None: ...
    def timer_sync_with_host(self) -> None: ...
    def timestamp_reset(self) -> None: ...
    def trigger_capture(self) -> None: ...
    def update_firmware(self, file_path: str, callback: Callable, async_update: bool = ...) -> None: ...
    def update_optional_depth_presets(self, file_path_list: list, callback: Callable) -> None: ...
    def __eq__(self, arg0: Device) -> bool: ...

class DeviceInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_connection_type(self) -> str: ...
    def get_device_gateway(self) -> str: ...
    def get_device_ip_address(self) -> str: ...
    def get_device_subnet_mask(self) -> str: ...
    def get_device_type(self) -> OBDeviceType: ...
    def get_firmware_version(self) -> str: ...
    def get_hardware_version(self) -> str: ...
    def get_name(self) -> str: ...
    def get_pid(self) -> int: ...
    def get_serial_number(self) -> str: ...
    def get_supported_min_sdk_version(self) -> str: ...
    def get_uid(self) -> str: ...
    def get_vid(self) -> int: ...

class DeviceList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_count(self) -> int: ...
    def get_device_by_index(self, *args, **kwargs): ...
    def get_device_by_serial_number(self, *args, **kwargs): ...
    def get_device_by_uid(self, *args, **kwargs): ...
    def get_device_connection_type_by_index(self, arg0: int) -> str: ...
    def get_device_gateway_by_index(self, arg0: int) -> str: ...
    def get_device_ip_address_by_index(self, arg0: int) -> str: ...
    def get_device_name_by_index(self, arg0: int) -> str: ...
    def get_device_pid_by_index(self, arg0: int) -> int: ...
    def get_device_serial_number_by_index(self, arg0: int) -> str: ...
    def get_device_subnet_mask_by_index(self, arg0: int) -> str: ...
    def get_device_uid_by_index(self, arg0: int) -> str: ...
    def get_device_vid_by_index(self, arg0: int) -> int: ...
    def get_local_gateway(self, arg0: int) -> str: ...
    def get_local_ip(self, arg0: int) -> str: ...
    def get_local_mac_address(self, arg0: int) -> str: ...
    def get_local_subnet_length(self, arg0: int) -> int: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...

class DevicePresetList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_count(self) -> int: ...
    def get_name_by_index(self, arg0: int) -> str: ...
    def has_preset(self, arg0: str) -> bool: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __getitem__(self, arg0: int) -> str: ...
    def __iter__(self) -> typing.Iterator[str]: ...
    def __len__(self) -> int: ...

class DisparityTransform(Filter):
    def __init__(self, activationKey: str = ...) -> None: ...

class Filter:
    def __init__(self, *args, **kwargs) -> None: ...
    def enable(self, arg0: bool) -> None: ...
    def get_config_schema_vec(self) -> list[OBFilterConfigSchemaItem]: ...
    def get_config_value(self, arg0: str) -> float: ...
    def get_name(self) -> str: ...
    def is_align_filter(self) -> bool: ...
    def is_decimation_filter(self) -> bool: ...
    def is_disparity_transform_filter(self) -> bool: ...
    def is_enabled(self) -> bool: ...
    def is_format_converter(self) -> bool: ...
    def is_hdr_merge_filter(self) -> bool: ...
    def is_hole_filling_filter(self) -> bool: ...
    def is_noise_removal_filter(self) -> bool: ...
    def is_point_cloud_filter(self) -> bool: ...
    def is_sequence_id_filter(self) -> bool: ...
    def is_spatial_advanced_filter(self) -> bool: ...
    def is_temporal_filter(self) -> bool: ...
    def is_threshold_filter(self) -> bool: ...
    def process(self, arg0) -> object: ...
    def push_frame(self, arg0) -> None: ...
    def reset(self) -> None: ...
    def set_callback(self, arg0: Callable) -> None: ...

class FormatConvertFilter(Filter):
    def __init__(self) -> None: ...
    def set_format_convert_format(self, arg0: OBConvertFormat) -> None: ...

class Frame:
    def __init__(self, *args, **kwargs) -> None: ...
    def as_accel_frame(self, *args, **kwargs): ...
    def as_color_frame(self, *args, **kwargs): ...
    def as_confidence_frame(self, *args, **kwargs): ...
    def as_depth_frame(self, *args, **kwargs): ...
    def as_frame_set(self, *args, **kwargs): ...
    def as_gyro_frame(self, *args, **kwargs): ...
    def as_ir_frame(self, *args, **kwargs): ...
    def as_lidar_points_frame(self, *args, **kwargs): ...
    def as_points_frame(self, *args, **kwargs): ...
    def as_video_frame(self, *args, **kwargs): ...
    def copy_frame_info(self, arg0: Frame) -> None: ...
    def get_data(self) -> numpy.ndarray[numpy.uint8]: ...
    def get_data_pointer(self) -> capsule: ...
    def get_data_size(self) -> int: ...
    def get_device(self) -> Device: ...
    def get_format(self) -> OBFormat: ...
    def get_global_timestamp_us(self) -> int: ...
    def get_index(self) -> int: ...
    def get_metadata_value(self, arg0: OBFrameMetadataType) -> int: ...
    def get_sensor(self, *args, **kwargs): ...
    def get_stream_profile(self, *args, **kwargs): ...
    def get_system_timestamp(self) -> int: ...
    def get_system_timestamp_us(self) -> int: ...
    def get_timestamp(self) -> int: ...
    def get_timestamp_us(self) -> int: ...
    def get_type(self) -> OBFrameType: ...
    def has_metadata(self, arg0: OBFrameMetadataType) -> bool: ...
    def set_stream_profile(self, arg0) -> None: ...
    def set_system_timestamp_us(self, arg0: int) -> None: ...
    def update_data(self, arg0: Buffer) -> None: ...
    def update_metadata(self, arg0: Buffer) -> None: ...

class FrameSet(Frame):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_color_frame(self) -> ColorFrame: ...
    def get_count(self) -> int: ...
    def get_depth_frame(self) -> DepthFrame: ...
    def get_frame(self, arg0: OBFrameType) -> Frame: ...
    def get_frame_by_index(self, arg0: int) -> Frame: ...
    def get_frame_by_type(self, arg0: OBFrameType) -> Frame: ...
    def get_frame_count(self) -> int: ...
    def get_ir_frame(self) -> IRFrame: ...
    def get_points_frame(self) -> PointsFrame: ...
    def push_frame(self, arg0: Frame) -> None: ...
    def __getitem__(self, arg0: int) -> Frame: ...
    def __iter__(self) -> typing.Iterator[Frame]: ...
    def __len__(self) -> int: ...

class GyroFrame(Frame):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_temperature(self) -> float: ...
    def get_value(self) -> OBAccelValue: ...
    def get_x(self) -> float: ...
    def get_y(self) -> float: ...
    def get_z(self) -> float: ...

class GyroStreamProfile(StreamProfile):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_full_scale_range(self) -> OBGyroFullScaleRange: ...
    def get_intrinsic(self) -> OBGyroIntrinsic: ...
    def get_sample_rate(self) -> OBGyroSampleRate: ...

class HDRMergeFilter(Filter):
    def __init__(self) -> None: ...

class HoleFillingFilter(Filter):
    def __init__(self) -> None: ...
    def get_filling_mode(self) -> OBHoleFillingMode: ...
    def set_filling_mode(self, arg0: OBHoleFillingMode) -> None: ...

class IRFrame(VideoFrame):
    def __init__(self, *args, **kwargs) -> None: ...

class LiDARPointsFrame(Frame):
    def __init__(self, *args, **kwargs) -> None: ...

class LiDARStreamProfile(StreamProfile):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_scan_rate(self) -> OBLiDARScanRate: ...

class NoiseRemovalFilter(Filter):
    def __init__(self) -> None: ...
    def get_disp_diff_range(self) -> OBUint16PropertyRange: ...
    def get_filter_params(self) -> OBNoiseRemovalFilterParams: ...
    def get_max_size_range(self) -> OBUint16PropertyRange: ...
    def set_filter_params(self, arg0: OBNoiseRemovalFilterParams) -> None: ...

class OBAccelFullScaleRange:
    __members__: ClassVar[dict] = ...  # read-only
    ACCEL_FS_16g: ClassVar[OBAccelFullScaleRange] = ...
    ACCEL_FS_2g: ClassVar[OBAccelFullScaleRange] = ...
    ACCEL_FS_4g: ClassVar[OBAccelFullScaleRange] = ...
    ACCEL_FS_8g: ClassVar[OBAccelFullScaleRange] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBAccelIntrinsic:
    bias: numpy.ndarray[numpy.float64]
    gravity: numpy.ndarray[numpy.float64]
    noise_density: float
    random_walk: float
    reference_temp: float
    scale_misalignment: numpy.ndarray[numpy.float64]
    temp_slope: numpy.ndarray[numpy.float64]
    def __init__(self) -> None: ...

class OBAccelSampleRate:
    __members__: ClassVar[dict] = ...  # read-only
    SAMPLE_RATE_100_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_12_5_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_16_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_1_5625_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_1_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_200_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_25_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_2_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_32_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_3_125_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_4_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_500_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_50_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_6_25_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_8_KHZ: ClassVar[OBGyroSampleRate] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBAccelValue:
    x: float
    y: float
    z: float
    def __init__(self) -> None: ...

class OBAlignMode:
    __members__: ClassVar[dict] = ...  # read-only
    DISABLE: ClassVar[OBAlignMode] = ...
    HW_MODE: ClassVar[OBAlignMode] = ...
    SW_MODE: ClassVar[OBAlignMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBBaselineCalibrationParam:
    baseline: float
    zpd: float
    def __init__(self) -> None: ...

class OBCalibrationParam:
    def __init__(self) -> None: ...
    def get_distortion(self, arg0: int) -> OBCameraDistortion: ...
    def get_extrinsic(self, arg0: int, arg1: int) -> OBExtrinsic: ...
    def get_intrinsic(self, arg0: int) -> OBCameraIntrinsic: ...
    def set_distortion(self, arg0: int, arg1: OBCameraDistortion) -> None: ...
    def set_extrinsic(self, arg0: int, arg1: int, arg2: OBExtrinsic) -> None: ...
    def set_intrinsic(self, arg0: int, arg1: OBCameraIntrinsic) -> None: ...

class OBCameraDistortion:
    k1: float
    k2: float
    k3: float
    k4: float
    k5: float
    k6: float
    p1: float
    p2: float
    def __init__(self) -> None: ...

class OBCameraDistortionModel:
    __members__: ClassVar[dict] = ...  # read-only
    BROWN_CONRADY: ClassVar[OBCameraDistortionModel] = ...
    INVERSE_BROWN_CONRADY: ClassVar[OBCameraDistortionModel] = ...
    MODIFIED_BROWN_CONRADY: ClassVar[OBCameraDistortionModel] = ...
    NONE: ClassVar[OBCameraDistortionModel] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBCameraIntrinsic:
    cx: float
    cy: float
    fx: float
    fy: float
    height: int
    width: int
    def __init__(self) -> None: ...

class OBCameraParam:
    depth_distortion: OBCameraDistortion
    depth_intrinsic: OBCameraIntrinsic
    rgb_distortion: OBCameraDistortion
    rgb_intrinsic: OBCameraIntrinsic
    transform: OBExtrinsic
    def __init__(self) -> None: ...

class OBCmdVersion:
    __members__: ClassVar[dict] = ...  # read-only
    INVALID: ClassVar[OBCmdVersion] = ...
    NONE: ClassVar[OBCmdVersion] = ...
    V0: ClassVar[OBCmdVersion] = ...
    V1: ClassVar[OBCmdVersion] = ...
    V2: ClassVar[OBCmdVersion] = ...
    V3: ClassVar[OBCmdVersion] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBColorPoint:
    b: int
    g: int
    r: int
    x: float
    y: float
    z: float
    def __init__(self) -> None: ...
    @staticmethod
    def get_sizeof() -> int: ...

class OBCommunicationType:
    __members__: ClassVar[dict] = ...  # read-only
    ETHERNET: ClassVar[OBCommunicationType] = ...
    USB: ClassVar[OBCommunicationType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBCompressionMode:
    __members__: ClassVar[dict] = ...  # read-only
    LOSSLESS: ClassVar[OBCompressionMode] = ...
    LOSSY: ClassVar[OBCompressionMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBCompressionParams:
    threshold: int
    def __init__(self) -> None: ...

class OBConvertFormat:
    __members__: ClassVar[dict] = ...  # read-only
    BGR_TO_RGB: ClassVar[OBConvertFormat] = ...
    I420_TO_RGB888: ClassVar[OBConvertFormat] = ...
    MJPG_TO_BGR888: ClassVar[OBConvertFormat] = ...
    MJPG_TO_BGRA: ClassVar[OBConvertFormat] = ...
    MJPG_TO_I420: ClassVar[OBConvertFormat] = ...
    MJPG_TO_NV21: ClassVar[OBConvertFormat] = ...
    MJPG_TO_RGB888: ClassVar[OBConvertFormat] = ...
    NV12_TO_RGB888: ClassVar[OBConvertFormat] = ...
    NV21_TO_RGB888: ClassVar[OBConvertFormat] = ...
    RGB888_TO_BGR: ClassVar[OBConvertFormat] = ...
    UYVY_TO_RGB888: ClassVar[OBConvertFormat] = ...
    YUYV_TO_RGB888: ClassVar[OBConvertFormat] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBCoordinateSystemType:
    __members__: ClassVar[dict] = ...  # read-only
    LEFT_HAND: ClassVar[OBCoordinateSystemType] = ...
    RIGHT_HAND: ClassVar[OBCoordinateSystemType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDCPowerState:
    __members__: ClassVar[dict] = ...  # read-only
    OFF: ClassVar[OBDCPowerState] = ...
    ON: ClassVar[OBDCPowerState] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDDONoiseRemovalType:
    __members__: ClassVar[dict] = ...  # read-only
    LUT: ClassVar[OBDDONoiseRemovalType] = ...
    OVERALL: ClassVar[OBDDONoiseRemovalType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDataTranState:
    __members__: ClassVar[dict] = ...  # read-only
    DONE: ClassVar[OBDataTranState] = ...
    ERR_BUSY: ClassVar[OBDataTranState] = ...
    ERR_OTHER: ClassVar[OBDataTranState] = ...
    ERR_TRAN_FAILED: ClassVar[OBDataTranState] = ...
    ERR_UNSUPPORTED: ClassVar[OBDataTranState] = ...
    ERR_VERIFY_FAILED: ClassVar[OBDataTranState] = ...
    STOPPED: ClassVar[OBDataTranState] = ...
    TRANSFERRING: ClassVar[OBDataTranState] = ...
    VERIFYING: ClassVar[OBDataTranState] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDepthCroppingMode:
    __members__: ClassVar[dict] = ...  # read-only
    AUTO: ClassVar[OBDepthCroppingMode] = ...
    CLOSE: ClassVar[OBDepthCroppingMode] = ...
    OPEN: ClassVar[OBDepthCroppingMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDepthPrecisionLevel:
    __members__: ClassVar[dict] = ...  # read-only
    ONE_MM: ClassVar[OBDepthPrecisionLevel] = ...
    ZERO_POINT_EIGHT_MM: ClassVar[OBDepthPrecisionLevel] = ...
    ZERO_POINT_FOUR_MM: ClassVar[OBDepthPrecisionLevel] = ...
    ZERO_POINT_ONE_MM: ClassVar[OBDepthPrecisionLevel] = ...
    ZERO_POINT_TWO_MM: ClassVar[OBDepthPrecisionLevel] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDepthWorkMode:
    checksum: numpy.ndarray[numpy.uint8]
    name: str
    tag: OBDepthWorkModeTag
    def __init__(self) -> None: ...
    def __eq__(self, arg0: OBDepthWorkMode) -> bool: ...

class OBDepthWorkModeList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_count(self) -> int: ...
    def get_depth_work_mode_by_index(self, arg0: int) -> OBDepthWorkMode: ...
    def __getitem__(self, arg0: int) -> OBDepthWorkMode: ...
    def __iter__(self) -> typing.Iterator[OBDepthWorkMode]: ...
    def __len__(self) -> int: ...

class OBDepthWorkModeTag:
    __members__: ClassVar[dict] = ...  # read-only
    OB_CUSTOM_DEPTH_WORK_MODE: ClassVar[OBDepthWorkModeTag] = ...
    OB_DEVICE_DEPTH_WORK_MODE: ClassVar[OBDepthWorkModeTag] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDeviceAccessMode:
    __members__: ClassVar[dict] = ...  # read-only
    OB_DEVICE_ACCESS_DENIED: ClassVar[OBDeviceAccessMode] = ...
    OB_DEVICE_CONTROL_ACCESS: ClassVar[OBDeviceAccessMode] = ...
    OB_DEVICE_DEFAULT_ACCESS: ClassVar[OBDeviceAccessMode] = ...
    OB_DEVICE_EXCLUSIVE_ACCESS: ClassVar[OBDeviceAccessMode] = ...
    OB_DEVICE_MONITOR_ACCESS: ClassVar[OBDeviceAccessMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDeviceDevelopmentMode:
    __members__: ClassVar[dict] = ...  # read-only
    DEVELOPMENT: ClassVar[OBDeviceDevelopmentMode] = ...
    NORMAL: ClassVar[OBDeviceDevelopmentMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBDeviceIpAddrConfig:
    address: str
    dhcp: int
    gateway: str
    netmask: str
    def __init__(self) -> None: ...

class OBDeviceSyncConfig:
    device_index: int
    device_trigger_signal_out_delay: int
    device_trigger_signal_out_polarity: int
    ir_trigger_signal_delay: int
    mcu_trigger_frequency: int
    mode: OBSyncMode
    rgb_trigger_signal_delay: int
    def __init__(self) -> None: ...

class OBDeviceTemperature:
    chip_bottom_temperature: float
    chip_top_temperature: float
    cpu_temperature: float
    imu_temperature: float
    ir_left_temperature: float
    ir_right_temperature: float
    ir_temperature: float
    laser_temperature: float
    main_board_temperature: float
    rgb_temperature: float
    tec_temperature: float
    def __init__(self) -> None: ...

class OBDeviceTimestampResetConfig:
    enable: bool
    timestamp_reset_delay_us: int
    def __init__(self) -> None: ...

class OBDeviceType:
    __members__: ClassVar[dict] = ...  # read-only
    LIGHT_BINOCULAR: ClassVar[OBDeviceType] = ...
    LIGHT_MONOCULAR: ClassVar[OBDeviceType] = ...
    TIME_OF_FLIGHT: ClassVar[OBDeviceType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBEdgeNoiseRemovalFilterParams:
    margin_bottom_th: int
    margin_left_th: int
    margin_right_th: int
    margin_top_th: int
    type: OBEdgeNoiseRemovalType
    def __init__(self) -> None: ...

class OBEdgeNoiseRemovalType:
    __members__: ClassVar[dict] = ...  # read-only
    MGA_FILTER: ClassVar[OBEdgeNoiseRemovalType] = ...
    MGC_FILTER: ClassVar[OBEdgeNoiseRemovalType] = ...
    MGH_FILTER: ClassVar[OBEdgeNoiseRemovalType] = ...
    MG_FILTER: ClassVar[OBEdgeNoiseRemovalType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBError(Exception): ...

class OBException:
    __members__: ClassVar[dict] = ...  # read-only
    CAMERA_DISCONNECTED: ClassVar[OBException] = ...
    INVALID_VALUE: ClassVar[OBException] = ...
    IO_ERROR: ClassVar[OBException] = ...
    NOT_IMPLEMENTED: ClassVar[OBException] = ...
    PLATFORM: ClassVar[OBException] = ...
    UNKNOWN: ClassVar[OBException] = ...
    WRONG_API_CALL_SEQUENCE: ClassVar[OBException] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBExtrinsic:
    rot: numpy.ndarray[numpy.float32]
    transform: numpy.ndarray[numpy.float32]
    def __init__(self) -> None: ...

class OBFileTranState:
    __members__: ClassVar[dict] = ...  # read-only
    DONE: ClassVar[OBFileTranState] = ...
    ERR_DDR: ClassVar[OBFileTranState] = ...
    ERR_MD5_ERROR: ClassVar[OBFileTranState] = ...
    ERR_NOT_ENOUGH_SPACE: ClassVar[OBFileTranState] = ...
    ERR_PATH_NOT_WRITABLE: ClassVar[OBFileTranState] = ...
    ERR_TIMEOUT: ClassVar[OBFileTranState] = ...
    ERR_WRITE_FLASH_ERROR: ClassVar[OBFileTranState] = ...
    PREPARING: ClassVar[OBFileTranState] = ...
    TRANSFER: ClassVar[OBFileTranState] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBFilterConfigSchemaItem:
    default: float
    max: float
    min: float
    step: float
    type: OBFilterConfigValueType
    def __init__(self) -> None: ...
    @property
    def desc(self) -> str: ...
    @property
    def name(self) -> str: ...

class OBFilterConfigValueType:
    __members__: ClassVar[dict] = ...  # read-only
    BOOLEAN: ClassVar[OBFilterConfigValueType] = ...
    FLOAT: ClassVar[OBFilterConfigValueType] = ...
    INT: ClassVar[OBFilterConfigValueType] = ...
    INVALID: ClassVar[OBFilterConfigValueType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBFilterList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_count(self) -> int: ...
    def get_filter(self, arg0: int) -> Filter: ...
    def __getitem__(self, arg0: int) -> Filter: ...
    def __iter__(self) -> typing.Iterator[Filter]: ...
    def __len__(self) -> int: ...

class OBFloat3D:
    x: float
    y: float
    z: float
    def __init__(self) -> None: ...

class OBFloatPropertyRange:
    current: float
    default_value: float
    max: float
    min: float
    step: float
    def __init__(self) -> None: ...

class OBFormat:
    __members__: ClassVar[dict] = ...  # read-only
    ACCEL: ClassVar[OBFormat] = ...
    BA81: ClassVar[OBFormat] = ...
    BGR: ClassVar[OBFormat] = ...
    BGRA: ClassVar[OBFormat] = ...
    BYR2: ClassVar[OBFormat] = ...
    COMPRESSED: ClassVar[OBFormat] = ...
    GRAY: ClassVar[OBFormat] = ...
    GYRO: ClassVar[OBFormat] = ...
    H264: ClassVar[OBFormat] = ...
    H265: ClassVar[OBFormat] = ...
    HEVC: ClassVar[OBFormat] = ...
    I420: ClassVar[OBFormat] = ...
    LIDAR_CALIBRATION: ClassVar[OBFormat] = ...
    LIDAR_POINT: ClassVar[OBFormat] = ...
    LIDAR_SCAN: ClassVar[OBFormat] = ...
    LIDAR_SPHERE_POINT: ClassVar[OBFormat] = ...
    MJPG: ClassVar[OBFormat] = ...
    NV12: ClassVar[OBFormat] = ...
    NV21: ClassVar[OBFormat] = ...
    POINT: ClassVar[OBFormat] = ...
    RGB: ClassVar[OBFormat] = ...
    RGBA: ClassVar[OBFormat] = ...
    RGB_POINT: ClassVar[OBFormat] = ...
    RLE: ClassVar[OBFormat] = ...
    RVL: ClassVar[OBFormat] = ...
    RW16: ClassVar[OBFormat] = ...
    UNKNOWN_FORMAT: ClassVar[OBFormat] = ...
    UYVY: ClassVar[OBFormat] = ...
    Y10: ClassVar[OBFormat] = ...
    Y11: ClassVar[OBFormat] = ...
    Y12: ClassVar[OBFormat] = ...
    Y12C4: ClassVar[OBFormat] = ...
    Y14: ClassVar[OBFormat] = ...
    Y16: ClassVar[OBFormat] = ...
    Y8: ClassVar[OBFormat] = ...
    YUY2: ClassVar[OBFormat] = ...
    YUYV: ClassVar[OBFormat] = ...
    YV12: ClassVar[OBFormat] = ...
    Z16: ClassVar[OBFormat] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBFrameAggregateOutputMode:
    __members__: ClassVar[dict] = ...  # read-only
    ANY_SITUATION: ClassVar[OBFrameAggregateOutputMode] = ...
    COLOR_FRAME_REQUIRE: ClassVar[OBFrameAggregateOutputMode] = ...
    DISABLE: ClassVar[OBFrameAggregateOutputMode] = ...
    FULL_FRAME_REQUIRE: ClassVar[OBFrameAggregateOutputMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBFrameMetadataType:
    __members__: ClassVar[dict] = ...  # read-only
    ACTUAL_FRAME_RATE: ClassVar[OBFrameMetadataType] = ...
    AE_ROI_BOTTOM: ClassVar[OBFrameMetadataType] = ...
    AE_ROI_LEFT: ClassVar[OBFrameMetadataType] = ...
    AE_ROI_RIGHT: ClassVar[OBFrameMetadataType] = ...
    AE_ROI_TOP: ClassVar[OBFrameMetadataType] = ...
    AUTO_EXPOSURE: ClassVar[OBFrameMetadataType] = ...
    AUTO_WHITE_BALANCE: ClassVar[OBFrameMetadataType] = ...
    BACKLIGHT_COMPENSATION: ClassVar[OBFrameMetadataType] = ...
    BRIGHTNESS: ClassVar[OBFrameMetadataType] = ...
    CONTRAST: ClassVar[OBFrameMetadataType] = ...
    COUNT: ClassVar[OBFrameMetadataType] = ...
    DISPARITY_SEARCH_OFFSET: ClassVar[OBFrameMetadataType] = ...
    DISPARITY_SEARCH_RANGE: ClassVar[OBFrameMetadataType] = ...
    EXPOSURE: ClassVar[OBFrameMetadataType] = ...
    EXPOSURE_PRIORITY: ClassVar[OBFrameMetadataType] = ...
    FRAME_NUMBER: ClassVar[OBFrameMetadataType] = ...
    FRAME_RATE: ClassVar[OBFrameMetadataType] = ...
    GAIN: ClassVar[OBFrameMetadataType] = ...
    GAMMA: ClassVar[OBFrameMetadataType] = ...
    GPIO_INPUT_DATA: ClassVar[OBFrameMetadataType] = ...
    HDR_SEQUENCE_INDEX: ClassVar[OBFrameMetadataType] = ...
    HDR_SEQUENCE_NAME: ClassVar[OBFrameMetadataType] = ...
    HDR_SEQUENCE_SIZE: ClassVar[OBFrameMetadataType] = ...
    HUE: ClassVar[OBFrameMetadataType] = ...
    LASER_POWER: ClassVar[OBFrameMetadataType] = ...
    LASER_POWER_LEVEL: ClassVar[OBFrameMetadataType] = ...
    LASER_STATUS: ClassVar[OBFrameMetadataType] = ...
    LOW_LIGHT_COMPENSATION: ClassVar[OBFrameMetadataType] = ...
    MANUAL_WHITE_BALANCE: ClassVar[OBFrameMetadataType] = ...
    POWER_LINE_FREQUENCY: ClassVar[OBFrameMetadataType] = ...
    SATURATION: ClassVar[OBFrameMetadataType] = ...
    SENSOR_TIMESTAMP: ClassVar[OBFrameMetadataType] = ...
    SHARPNESS: ClassVar[OBFrameMetadataType] = ...
    TIMESTAMP: ClassVar[OBFrameMetadataType] = ...
    WHITE_BALANCE: ClassVar[OBFrameMetadataType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBFrameType:
    __members__: ClassVar[dict] = ...  # read-only
    ACCEL_FRAME: ClassVar[OBFrameType] = ...
    COLOR_FRAME: ClassVar[OBFrameType] = ...
    CONFIDENCE_FRAME: ClassVar[OBFrameType] = ...
    DEPTH_FRAME: ClassVar[OBFrameType] = ...
    FRAME_SET: ClassVar[OBFrameType] = ...
    GYRO_FRAME: ClassVar[OBFrameType] = ...
    IR_FRAME: ClassVar[OBFrameType] = ...
    LEFT_COLOR_FRAME: ClassVar[OBFrameType] = ...
    LEFT_IR_FRAME: ClassVar[OBFrameType] = ...
    LIDAR_POINTS_FRAME: ClassVar[OBFrameType] = ...
    RAW_PHASE_FRAME: ClassVar[OBFrameType] = ...
    RIGHT_COLOR_FRAME: ClassVar[OBFrameType] = ...
    RIGHT_IR_FRAME: ClassVar[OBFrameType] = ...
    TYPE_COUNT_FRAME: ClassVar[OBFrameType] = ...
    UNKNOWN_FRAME: ClassVar[OBFrameType] = ...
    VIDEO_FRAME: ClassVar[OBFrameType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBGyroFullScaleRange:
    __members__: ClassVar[dict] = ...  # read-only
    FS_1000dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_125dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_16dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_2000dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_250dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_31dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_500dps: ClassVar[OBGyroFullScaleRange] = ...
    FS_62dps: ClassVar[OBGyroFullScaleRange] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBGyroIntrinsic:
    bias: numpy.ndarray[numpy.float64]
    noise_density: float
    random_walk: float
    reference_temp: float
    scale_misalignment: numpy.ndarray[numpy.float64]
    temp_slope: numpy.ndarray[numpy.float64]
    def __init__(self) -> None: ...

class OBGyroSampleRate:
    __members__: ClassVar[dict] = ...  # read-only
    SAMPLE_RATE_100_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_12_5_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_16_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_1_5625_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_1_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_200_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_25_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_2_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_32_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_3_125_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_4_KHZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_500_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_50_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_6_25_HZ: ClassVar[OBGyroSampleRate] = ...
    SAMPLE_RATE_8_KHZ: ClassVar[OBGyroSampleRate] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBGyroValue:
    x: float
    y: float
    z: float
    def __init__(self) -> None: ...

class OBHardwareDecimationConfig:
    factor: int
    origin_height: int
    origin_width: int
    def __init__(self) -> None: ...

class OBHdrConfig:
    enable: int
    exposure_1: int
    exposure_2: int
    gain_1: int
    gain_2: int
    sequence_name: int
    def __init__(self) -> None: ...

class OBHoleFillingMode:
    __members__: ClassVar[dict] = ...  # read-only
    FURTHEST: ClassVar[OBHoleFillingMode] = ...
    NEAREST: ClassVar[OBHoleFillingMode] = ...
    TOP: ClassVar[OBHoleFillingMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBIntPropertyRange:
    current: int
    default_value: int
    max: int
    min: int
    step: int
    def __init__(self) -> None: ...

class OBLiDARPoint:
    reflectivity: int
    tag: int
    x: float
    y: float
    z: float
    def __init__(self) -> None: ...

class OBLiDARScanPoint:
    angle: float
    distance: float
    intensity: int
    def __init__(self) -> None: ...

class OBLiDARScanRate:
    __members__: ClassVar[dict] = ...  # read-only
    LIDAR_SCAN_10HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_15HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_20HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_25HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_30HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_40HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_5HZ: ClassVar[OBLiDARScanRate] = ...
    LIDAR_SCAN_UNKNOWN: ClassVar[OBLiDARScanRate] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBLiDARSpherePoint:
    distance: float
    phi: float
    reflectivity: int
    tag: int
    theta: float
    def __init__(self) -> None: ...

class OBLogLevel:
    __members__: ClassVar[dict] = ...  # read-only
    DEBUG: ClassVar[OBLogLevel] = ...
    ERROR: ClassVar[OBLogLevel] = ...
    FATAL: ClassVar[OBLogLevel] = ...
    INFO: ClassVar[OBLogLevel] = ...
    NONE: ClassVar[OBLogLevel] = ...
    WARNING: ClassVar[OBLogLevel] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBMediaState:
    __members__: ClassVar[dict] = ...  # read-only
    OB_MEDIA_BEGIN: ClassVar[OBMediaState] = ...
    OB_MEDIA_END: ClassVar[OBMediaState] = ...
    OB_MEDIA_PAUSE: ClassVar[OBMediaState] = ...
    OB_MEDIA_RESUME: ClassVar[OBMediaState] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBMediaType:
    __members__: ClassVar[dict] = ...  # read-only
    ACCEL: ClassVar[OBMediaType] = ...
    CAMERA_PARAM: ClassVar[OBMediaType] = ...
    COLOR: ClassVar[OBMediaType] = ...
    DEPTH: ClassVar[OBMediaType] = ...
    DEVICE_INFO: ClassVar[OBMediaType] = ...
    GYRO: ClassVar[OBMediaType] = ...
    IR: ClassVar[OBMediaType] = ...
    LEFT_IR: ClassVar[OBMediaType] = ...
    RIGHT_IR: ClassVar[OBMediaType] = ...
    STREAM_INFO: ClassVar[OBMediaType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBMultiDeviceSyncConfig:
    color_delay_us: int
    depth_delay_us: int
    frames_per_trigger: int
    mode: OBMultiDeviceSyncMode
    trigger_out_delay_us: int
    trigger_out_enable: bool
    trigger_to_image_delay_us: int
    def __init__(self) -> None: ...

class OBMultiDeviceSyncMode:
    __members__: ClassVar[dict] = ...  # read-only
    FREE_RUN: ClassVar[OBMultiDeviceSyncMode] = ...
    HARDWARE_TRIGGERING: ClassVar[OBMultiDeviceSyncMode] = ...
    IR_IMU_SYNC: ClassVar[OBMultiDeviceSyncMode] = ...
    PRIMARY: ClassVar[OBMultiDeviceSyncMode] = ...
    SECONDARY: ClassVar[OBMultiDeviceSyncMode] = ...
    SECONDARY_SYNCED: ClassVar[OBMultiDeviceSyncMode] = ...
    SOFTWARE_SYNCED: ClassVar[OBMultiDeviceSyncMode] = ...
    SOFTWARE_TRIGGERING: ClassVar[OBMultiDeviceSyncMode] = ...
    STANDALONE: ClassVar[OBMultiDeviceSyncMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBNoiseRemovalFilterParams:
    disp_diff: int
    max_size: int
    type: OBDDONoiseRemovalType
    def __init__(self) -> None: ...

class OBPermissionType:
    __members__: ClassVar[dict] = ...  # read-only
    PERMISSION_DENY: ClassVar[OBPermissionType] = ...
    PERMISSION_READ: ClassVar[OBPermissionType] = ...
    PERMISSION_READ_WRITE: ClassVar[OBPermissionType] = ...
    PERMISSION_WRITE: ClassVar[OBPermissionType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBPixelType:
    __members__: ClassVar[dict] = ...  # read-only
    OB_PIXEL_DEPTH: ClassVar[OBPixelType] = ...
    OB_PIXEL_DISPARITY: ClassVar[OBPixelType] = ...
    OB_PIXEL_RAW_PHASE: ClassVar[OBPixelType] = ...
    OB_PIXEL_TOF_DEPTH: ClassVar[OBPixelType] = ...
    OB_PIXEL_UNKNOWN: ClassVar[OBPixelType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBPlaybackStatus:
    __members__: ClassVar[dict] = ...  # read-only
    COUNT: ClassVar[OBPlaybackStatus] = ...
    PAUSED: ClassVar[OBPlaybackStatus] = ...
    PLAYING: ClassVar[OBPlaybackStatus] = ...
    STOPPED: ClassVar[OBPlaybackStatus] = ...
    UNKNOWN: ClassVar[OBPlaybackStatus] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBPoint2f:
    x: float
    y: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float) -> None: ...

class OBPoint3f:
    x: float
    y: float
    z: float
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: float, arg1: float, arg2: float) -> None: ...
    @staticmethod
    def get_sizeof() -> int: ...

class OBPowerLineFreqMode:
    __members__: ClassVar[dict] = ...  # read-only
    FREQUENCY_50HZ: ClassVar[OBPowerLineFreqMode] = ...
    FREQUENCY_60HZ: ClassVar[OBPowerLineFreqMode] = ...
    FREQUENCY_CLOSE: ClassVar[OBPowerLineFreqMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBPresetResolutionConfig:
    depth_decimation_factor: int
    height: int
    ir_decimation_factor: int
    width: int
    def __init__(self) -> None: ...

class OBPropertyID:
    __members__: ClassVar[dict] = ...  # read-only
    OB_DEVICE_AUTO_CAPTURE_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_DEVICE_AUTO_CAPTURE_INTERVAL_TIME_INT: ClassVar[OBPropertyID] = ...
    OB_DEVICE_PTP_CLOCK_SYNC_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_ANTI_COLLUSION_ACTIVATION_STATUS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_BOOT_INTO_RECOVERY_MODE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_BRT_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_CAPTURE_IMAGE_FRAME_NUMBER_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_CAPTURE_IMAGE_NUMBER_INTERVAL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_CAPTURE_IMAGE_SIGNAL_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_CAPTURE_IMAGE_TIME_INTERVAL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_CAPTURE_INTERVAL_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_CHECK_PPS_SYNC_IN_SIGNAL_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_AE_MAX_EXPOSURE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_AUTO_EXPOSURE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_AUTO_EXPOSURE_PRIORITY_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_AUTO_WHITE_BALANCE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_BACKLIGHT_COMPENSATION_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_BRIGHTNESS_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_CONTRAST_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_EXPOSURE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_FLIP_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_FOCUS_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_GAIN_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_GAMMA_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_HDR_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_HUE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_MAXIMAL_GAIN_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_MAXIMAL_SHUTTER_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_MIRROR_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_POWER_LINE_FREQUENCY_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_ROLL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_ROTATE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_SATURATION_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_SHARPNESS_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_SHUTTER_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_COLOR_WHITE_BALANCE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_D2C_PREPROCESS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DC_POWER_STATE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEBUG_ESGM_CONFIDENCE_FLOAT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_ALIGN_HARDWARE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_ALIGN_HARDWARE_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_AUTO_EXPOSURE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_CROPPING_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_EXPOSURE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_FLIP_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_GAIN_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_HOLEFILTER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_MAX_DIFF_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_MAX_SPECKLE_SIZE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_MIRROR_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_NOISE_REMOVAL_FILTER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_NOISE_REMOVAL_FILTER_MAX_DIFF_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_NOISE_REMOVAL_FILTER_MAX_SPECKLE_SIZE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_POSTFILTER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_PRECISION_LEVEL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_RM_FILTER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_ROTATE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_SOFT_FILTER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEPTH_UNIT_FLEXIBLE_ADJUSTMENT_FLOAT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_COMMUNICATION_TYPE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_DEVELOPMENT_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_IN_RECOVERY_MODE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_REBOOT_DELAY_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_REPOWER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_USB3_REPEAT_IDENTIFY_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DEVICE_WORK_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DISPARITY_TO_DEPTH_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_DISP_SEARCH_OFFSET_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_DISP_SEARCH_RANGE_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_EXTERNAL_SIGNAL_RESET_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_FAN_WORK_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_FLOOD_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_FLOOD_LEVEL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_FRAME_INTERLEAVE_CONFIG_INDEX_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_FRAME_INTERLEAVE_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_FRAME_INTERLEAVE_LASER_PATTERN_SYNC_DELAY_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_HARDWARE_DISTORTION_SWITCH_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_HDR_MERGE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_HEARTBEAT_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_HW_NOISE_REMOVE_FILTER_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_HW_NOISE_REMOVE_FILTER_THRESHOLD_FLOAT: ClassVar[OBPropertyID] = ...
    OB_PROP_INDICATOR_LIGHT_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_AE_MAX_EXPOSURE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_AUTO_EXPOSURE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_BRIGHTNESS_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_CHANNEL_DATA_SOURCE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_EXPOSURE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_FLIP_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_GAIN_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_LONG_EXPOSURE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_MIRROR_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_RECTIFY_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_RIGHT_FLIP_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_RIGHT_MIRROR_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_RIGHT_ROTATE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_ROTATE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_IR_SHORT_EXPOSURE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_ALWAYS_ON_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_CONTROL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_CURRENT_FLOAT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_ENERGY_LEVEL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_HIGH_TEMPERATURE_PROTECT_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_HW_ENERGY_LEVEL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_ON_OFF_PATTERN_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_OVERCURRENT_PROTECTION_STATUS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_POWER_LEVEL_CONTROL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_PULSE_WIDTH_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LASER_PULSE_WIDTH_PROTECTION_STATUS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LDP_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LDP_MEASURE_DISTANCE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LDP_STATUS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_LIDAR_TAIL_FILTER_LEVEL_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_LOW_EXPOSURE_LASER_CONTROL_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_MAX_DEPTH_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_MIN_DEPTH_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_ON_CHIP_CALIBRATION_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_ON_CHIP_CALIBRATION_HEALTH_CHECK_FLOAT: ClassVar[OBPropertyID] = ...
    OB_PROP_RECTIFY2_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_RESTORE_FACTORY_SETTINGS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_RGB_CUSTOM_CROP_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_ACCEL_FRAME_TRANSFORMED_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_DEPTH_FRAME_UNPACK_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_DISPARITY_TO_DEPTH_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_GYRO_FRAME_TRANSFORMED_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_IR_FRAME_UNPACK_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_IR_LEFT_FRAME_UNPACK_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SDK_IR_RIGHT_FRAME_UNPACK_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SKIP_FRAME_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SLAVE_DEVICE_SYNC_STATUS_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_SWITCH_IR_MODE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_SYNC_SIGNAL_TRIGGER_OUT_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_TIMER_RESET_DELAY_US_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_TIMER_RESET_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_TIMER_RESET_SIGNAL_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_TIMER_RESET_TRIGGER_OUT_ENABLE_BOOL: ClassVar[OBPropertyID] = ...
    OB_PROP_TIMESTAMP_OFFSET_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_TOF_FILTER_RANGE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_USB_POWER_STATE_INT: ClassVar[OBPropertyID] = ...
    OB_PROP_WATCHDOG_BOOL: ClassVar[OBPropertyID] = ...
    OB_RAW_DATA_CAMERA_CALIB_JSON_FILE: ClassVar[OBPropertyID] = ...
    OB_STRUCT_ASIC_SERIAL_NUMBER: ClassVar[OBPropertyID] = ...
    OB_STRUCT_BASELINE_CALIBRATION_PARAM: ClassVar[OBPropertyID] = ...
    OB_STRUCT_COLOR_AE_ROI: ClassVar[OBPropertyID] = ...
    OB_STRUCT_CURRENT_DEPTH_ALG_MODE: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEPTH_AE_ROI: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEPTH_HDR_CONFIG: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEPTH_PRECISION_SUPPORT_LIST: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEVICE_IP_ADDR_CONFIG: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEVICE_SERIAL_NUMBER: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEVICE_STATIC_IP_CONFIG_RECORD: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEVICE_TEMPERATURE: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DEVICE_TIME: ClassVar[OBPropertyID] = ...
    OB_STRUCT_DISP_OFFSET_CONFIG: ClassVar[OBPropertyID] = ...
    OB_STRUCT_MULTI_DEVICE_SYNC_CONFIG: ClassVar[OBPropertyID] = ...
    OB_STRUCT_RGB_CROP_ROI: ClassVar[OBPropertyID] = ...
    OB_STRUCT_TOF_EXPOSURE_THRESHOLD_CONTROL: ClassVar[OBPropertyID] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBPropertyItem:
    id: OBPropertyID
    name: str
    permission: OBPermissionType
    type: OBPropertyType
    def __init__(self) -> None: ...

class OBPropertyType:
    __members__: ClassVar[dict] = ...  # read-only
    OB_BOOL_PROPERTY: ClassVar[OBPropertyType] = ...
    OB_FLOAT_PROPERTY: ClassVar[OBPropertyType] = ...
    OB_INT_PROPERTY: ClassVar[OBPropertyType] = ...
    OB_STRUCT_PROPERTY: ClassVar[OBPropertyType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBProtocolVersion:
    major: int
    minor: int
    patch: int
    def __init__(self) -> None: ...

class OBRect:
    height: int
    width: int
    x: int
    y: int
    def __init__(self) -> None: ...

class OBRegionOfInterest:
    x0_left: int
    x1_right: int
    y0_top: int
    y1_bottom: int
    def __init__(self) -> None: ...

class OBRotateDegreeType:
    __members__: ClassVar[dict] = ...  # read-only
    ROTATE_0: ClassVar[OBRotateDegreeType] = ...
    ROTATE_180: ClassVar[OBRotateDegreeType] = ...
    ROTATE_270: ClassVar[OBRotateDegreeType] = ...
    ROTATE_90: ClassVar[OBRotateDegreeType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBSensorType:
    __members__: ClassVar[dict] = ...  # read-only
    ACCEL_SENSOR: ClassVar[OBSensorType] = ...
    COLOR_SENSOR: ClassVar[OBSensorType] = ...
    CONFIDENCE_SENSOR: ClassVar[OBSensorType] = ...
    DEPTH_SENSOR: ClassVar[OBSensorType] = ...
    GYRO_SENSOR: ClassVar[OBSensorType] = ...
    IR_SENSOR: ClassVar[OBSensorType] = ...
    LEFT_COLOR_SENSOR: ClassVar[OBSensorType] = ...
    LEFT_IR_SENSOR: ClassVar[OBSensorType] = ...
    LIDAR_SENSOR: ClassVar[OBSensorType] = ...
    RAW_PHASE_SENSOR: ClassVar[OBSensorType] = ...
    RIGHT_COLOR_SENSOR: ClassVar[OBSensorType] = ...
    RIGHT_IR_SENSOR: ClassVar[OBSensorType] = ...
    TYPE_COUNT_SENSOR: ClassVar[OBSensorType] = ...
    UNKNOWN_SENSOR: ClassVar[OBSensorType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBSequenceIdItem:
    name: str
    sequence_select_id: int
    def __init__(self) -> None: ...

class OBSpatialAdvancedFilterParams:
    alpha: float
    disp_diff: int
    magnitude: int
    radius: int
    def __init__(self) -> None: ...

class OBStatus:
    __members__: ClassVar[dict] = ...  # read-only
    STATUS_ERROR: ClassVar[OBStatus] = ...
    STATUS_OK: ClassVar[OBStatus] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBStreamType:
    __members__: ClassVar[dict] = ...  # read-only
    ACCEL_STREAM: ClassVar[OBStreamType] = ...
    COLOR_STREAM: ClassVar[OBStreamType] = ...
    CONFIDENCE_STREAM: ClassVar[OBStreamType] = ...
    DEPTH_STREAM: ClassVar[OBStreamType] = ...
    GYRO_STREAM: ClassVar[OBStreamType] = ...
    IR_STREAM: ClassVar[OBStreamType] = ...
    LEFT_COLOR_STREAM: ClassVar[OBStreamType] = ...
    LEFT_IR_STREAM: ClassVar[OBStreamType] = ...
    LIDAR_STREAM: ClassVar[OBStreamType] = ...
    RAW_PHASE_STREAM: ClassVar[OBStreamType] = ...
    RIGHT_COLOR_STREAM: ClassVar[OBStreamType] = ...
    RIGHT_IR_STREAM: ClassVar[OBStreamType] = ...
    TYPE_COUNT_STREAM: ClassVar[OBStreamType] = ...
    UNKNOWN_STREAM: ClassVar[OBStreamType] = ...
    VIDEO_STREAM: ClassVar[OBStreamType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBSyncMode:
    __members__: ClassVar[dict] = ...  # read-only
    CLOSE: ClassVar[OBSyncMode] = ...
    IR_IMU_SYNC: ClassVar[OBSyncMode] = ...
    PRIMARY: ClassVar[OBSyncMode] = ...
    PRIMARY_IR_TRIGGER: ClassVar[OBSyncMode] = ...
    PRIMARY_MCU_TRIGGER: ClassVar[OBSyncMode] = ...
    PRIMARY_SOFT_TRIGGER: ClassVar[OBSyncMode] = ...
    SECONDARY: ClassVar[OBSyncMode] = ...
    SECONDARY_SOFT_TRIGGER: ClassVar[OBSyncMode] = ...
    STANDALONE: ClassVar[OBSyncMode] = ...
    UNKNOWN: ClassVar[OBSyncMode] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBTofExposureThresholdControl:
    lower: int
    upper: int
    def __init__(self) -> None: ...

class OBTofFilterRange:
    __members__: ClassVar[dict] = ...  # read-only
    CLOSE: ClassVar[OBTofFilterRange] = ...
    DEBUG: ClassVar[OBTofFilterRange] = ...
    FAR: ClassVar[OBTofFilterRange] = ...
    MIDDLE: ClassVar[OBTofFilterRange] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBUSBPowerState:
    __members__: ClassVar[dict] = ...  # read-only
    OFF: ClassVar[OBUSBPowerState] = ...
    POWER_5V_0A9: ClassVar[OBUSBPowerState] = ...
    POWER_5V_1A5: ClassVar[OBUSBPowerState] = ...
    POWER_5V_3A0: ClassVar[OBUSBPowerState] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class OBUint16PropertyRange:
    current: int
    default_value: int
    max: int
    min: int
    step: int
    def __init__(self) -> None: ...

class OBUint8PropertyRange:
    current: int
    default_value: int
    max: int
    min: int
    step: int
    def __init__(self) -> None: ...

class OBUpgradeState:
    __members__: ClassVar[dict] = ...  # read-only
    DONE: ClassVar[OBUpgradeState] = ...
    DONE_REBOOT_AND_REUPDATE: ClassVar[OBUpgradeState] = ...
    DONE_WITH_DUPLICATES: ClassVar[OBUpgradeState] = ...
    ERR_DDR: ClassVar[OBUpgradeState] = ...
    ERR_ERASE: ClassVar[OBUpgradeState] = ...
    ERR_FILE_READ: ClassVar[OBUpgradeState] = ...
    ERR_FLASH_TYPE: ClassVar[OBUpgradeState] = ...
    ERR_IMAGE_SIZE: ClassVar[OBUpgradeState] = ...
    ERR_INVALID_COUNT: ClassVar[OBUpgradeState] = ...
    ERR_MISMATCH: ClassVar[OBUpgradeState] = ...
    ERR_OTHER: ClassVar[OBUpgradeState] = ...
    ERR_PROGRAM: ClassVar[OBUpgradeState] = ...
    ERR_TIMEOUT: ClassVar[OBUpgradeState] = ...
    ERR_TRANSFER: ClassVar[OBUpgradeState] = ...
    ERR_UNSUPPORT_DEV: ClassVar[OBUpgradeState] = ...
    ERR_VERIFY: ClassVar[OBUpgradeState] = ...
    FILE_TRANSFER: ClassVar[OBUpgradeState] = ...
    IN_PROGRESS: ClassVar[OBUpgradeState] = ...
    START: ClassVar[OBUpgradeState] = ...
    VERIFY_IMAGE: ClassVar[OBUpgradeState] = ...
    VERIFY_SUCCESS: ClassVar[OBUpgradeState] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Pipeline:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: Device) -> None: ...
    def disable_frame_sync(self) -> None: ...
    def enable_frame_sync(self) -> None: ...
    def get_camera_param(self) -> OBCameraParam: ...
    def get_config(self, *args, **kwargs): ...
    def get_d2c_depth_profile_list(self, *args, **kwargs): ...
    def get_device(self) -> Device: ...
    def get_stream_profile_list(self, *args, **kwargs): ...
    @overload
    def start(self, arg0) -> None: ...
    @overload
    def start(self, arg0, arg1: Callable) -> None: ...
    @overload
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def wait_for_frames(self, arg0: int) -> FrameSet: ...

class PlaybackDevice(Device):
    def __init__(self, file: str) -> None: ...
    def get_duration(self) -> int: ...
    def get_playback_status(self) -> OBPlaybackStatus: ...
    def get_position(self) -> int: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def seek(self, timestamp: int) -> None: ...
    def set_playback_rate(self, rate: float) -> None: ...
    def set_playback_status_change_callback(self, arg0: Callable) -> None: ...

class PointCloudFilter(Filter):
    def __init__(self) -> None: ...
    def calculate(self, arg0) -> numpy.ndarray[numpy.float32]: ...
    def get_decimation_factor_range(self) -> OBIntPropertyRange: ...
    def set_camera_param(self, arg0: OBCameraParam) -> None: ...
    def set_color_data_normalization(self, arg0: bool) -> None: ...
    def set_create_point_format(self, arg0: OBFormat) -> None: ...
    def set_decimation_factor(self, arg0: int) -> None: ...
    def set_frame_align_state(self, arg0: bool) -> None: ...
    def set_position_data_scaled(self, arg0: float) -> None: ...

class PointsFrame(Frame):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_height(self) -> int: ...
    def get_position_value_scale(self) -> float: ...
    def get_width(self) -> int: ...

class PresetResolutionConfigList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_count(self) -> int: ...
    def get_preset_resolution_ratio_config(self, arg0: int) -> OBPresetResolutionConfig: ...

class RecordDevice:
    def __init__(self, device: Device, file: str, compression: bool = ...) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

class Sensor:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_recommended_filters(self) -> list[Filter]: ...
    def get_stream_profile_list(self, *args, **kwargs): ...
    def get_type(self) -> OBSensorType: ...
    def start(self, arg0, arg1: Callable) -> None: ...
    def stop(self) -> None: ...
    def switch_profile(self, arg0) -> None: ...

class SensorList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_count(self) -> int: ...
    def get_sensor_by_index(self, arg0: int) -> Sensor: ...
    def get_sensor_by_type(self, arg0: OBSensorType) -> Sensor: ...
    def get_type_by_index(self, arg0: int) -> OBSensorType: ...
    def __getitem__(self, arg0: int) -> Sensor: ...
    def __iter__(self) -> typing.Iterator[Sensor]: ...
    def __len__(self) -> int: ...

class SequenceIdFilter(Filter):
    def __init__(self) -> None: ...
    def get_select_sequence_id(self) -> int: ...
    def get_sequence_id_list(self) -> list: ...
    def get_sequence_id_list_size(self) -> int: ...
    def select_sequence_id(self, arg0: int) -> None: ...

class SpatialAdvancedFilter(Filter):
    def __init__(self) -> None: ...
    def get_alpha_range(self) -> OBFloatPropertyRange: ...
    def get_disp_diff_range(self) -> OBUint16PropertyRange: ...
    def get_filter_params(self) -> OBSpatialAdvancedFilterParams: ...
    def get_magnitude_range(self) -> OBIntPropertyRange: ...
    def get_radius_range(self) -> OBUint16PropertyRange: ...
    def set_filter_params(self, arg0: OBSpatialAdvancedFilterParams) -> None: ...

class StreamProfile:
    def __init__(self, *args, **kwargs) -> None: ...
    def as_accel_stream_profile(self, *args, **kwargs): ...
    def as_gyro_stream_profile(self, *args, **kwargs): ...
    def as_lidar_stream_profile(self, *args, **kwargs): ...
    def as_video_stream_profile(self, *args, **kwargs): ...
    @overload
    def bind_extrinsic_to(self, arg0: StreamProfile, arg1: OBExtrinsic) -> None: ...
    @overload
    def bind_extrinsic_to(self, arg0: OBStreamType, arg1: OBExtrinsic) -> None: ...
    def get_extrinsic_to(self, arg0: StreamProfile) -> OBExtrinsic: ...
    def get_format(self) -> OBFormat: ...
    def get_type(self) -> OBStreamType: ...
    def is_accel_stream_profile(self) -> bool: ...
    def is_gyro_stream_profile(self) -> bool: ...
    def is_video_stream_profile(self) -> bool: ...

class StreamProfileList:
    def __init__(self, *args, **kwargs) -> None: ...
    def get_accel_stream_profile(self, arg0: OBAccelFullScaleRange, arg1: OBGyroSampleRate) -> AccelStreamProfile: ...
    def get_count(self) -> int: ...
    def get_default_video_stream_profile(self) -> VideoStreamProfile: ...
    def get_gyro_stream_profile(self, arg0: OBGyroFullScaleRange, arg1: OBGyroSampleRate) -> GyroStreamProfile: ...
    def get_lidar_stream_profile(self, arg0: OBLiDARScanRate, arg1: OBFormat) -> LiDARStreamProfile: ...
    def get_stream_profile_by_index(self, arg0: int) -> StreamProfile: ...
    @overload
    def get_video_stream_profile(self, width: int = ..., height: int = ..., format: OBFormat = ..., fps: int = ...) -> VideoStreamProfile: ...
    @overload
    def get_video_stream_profile(self, decimation_config: OBHardwareDecimationConfig, format: OBFormat = ..., fps: int = ...) -> VideoStreamProfile: ...
    def __getitem__(self, arg0: int) -> StreamProfile: ...
    def __iter__(self) -> typing.Iterator[StreamProfile]: ...
    def __len__(self) -> int: ...

class TemporalFilter(Filter):
    def __init__(self) -> None: ...
    def get_diff_scale_range(self) -> OBFloatPropertyRange: ...
    def get_weight_range(self) -> OBFloatPropertyRange: ...
    def set_diff_scale(self, arg0: float) -> None: ...
    def set_weight(self, arg0: float) -> None: ...

class ThresholdFilter(Filter):
    def __init__(self) -> None: ...
    def get_max_range(self) -> OBIntPropertyRange: ...
    def get_min_range(self) -> OBIntPropertyRange: ...
    def set_value_range(self, arg0: int, arg1: int) -> bool: ...

class VideoFrame(Frame):
    def __init__(self, *args, **kwargs) -> None: ...
    def as_color_frame(self, *args, **kwargs): ...
    def as_confidence_frame(self, *args, **kwargs): ...
    def as_depth_frame(self, *args, **kwargs): ...
    def as_ir_frame(self, *args, **kwargs): ...
    def as_points_frame(self, *args, **kwargs): ...
    def get_height(self) -> int: ...
    def get_metadata(self) -> numpy.ndarray[numpy.uint8]: ...
    def get_metadata_size(self) -> int: ...
    def get_pixel_available_bit_size(self) -> int: ...
    def get_pixel_type(self) -> OBPixelType: ...
    def get_width(self) -> int: ...
    def set_pixel_available_bit_size(self, arg0: int) -> None: ...
    def set_pixel_type(self, arg0: OBPixelType) -> None: ...

class VideoStreamProfile(StreamProfile):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_decimation_config(self) -> OBHardwareDecimationConfig: ...
    def get_distortion(self) -> OBCameraDistortion: ...
    def get_fps(self) -> int: ...
    def get_height(self) -> int: ...
    def get_intrinsic(self) -> OBCameraIntrinsic: ...
    def get_width(self) -> int: ...

def get_version() -> str: ...
def save_lidar_point_cloud_to_ply(arg0: str, arg1: LiDARPointsFrame, arg2: bool) -> None: ...
def save_point_cloud_to_ply(file_name: str, frame: Frame, save_binary: bool = ..., use_mesh: bool = ..., mesh_threshold: float = ...) -> None: ...
def transformation2dto2d(arg0: OBPoint2f, arg1: float, arg2: OBCameraIntrinsic, arg3: OBCameraDistortion, arg4: OBCameraIntrinsic, arg5: OBCameraDistortion, arg6: OBExtrinsic) -> OBPoint2f: ...
def transformation2dto3d(arg0: OBPoint2f, arg1: float, arg2: OBCameraIntrinsic, arg3: OBExtrinsic) -> OBPoint3f: ...
def transformation3dto2d(arg0: OBPoint3f, arg1: OBCameraIntrinsic, arg2: OBCameraDistortion, arg3: OBExtrinsic) -> OBPoint2f: ...
def transformation3dto3d(arg0: OBPoint3f, arg1: OBExtrinsic) -> OBPoint3f: ...
