"""
Running Instructions:

python scripts/visualize_csv_recording.py \
  --input-csv multi_csv/subordinate_pc/your_file.csv \
  --output-video multi_csv/subordinate_pc/your_file_visualized.mp4 \
  --fps 15 \
  --pressure-shape 3072,4096,4 \
  --depth-shape 512,512 \
  --scale 0.25

"""
import argparse
import csv
from pathlib import Path
from typing import Iterable, Optional, Sequence, Tuple

import cv2
import numpy as np


DEFAULT_RGB_SHAPE = (3072, 4096, 4)
DEFAULT_DEPTH_SHAPE = (512, 512)


def parse_shape(shape_text: str) -> Tuple[int, ...]:
    parts = tuple(int(part.strip()) for part in shape_text.split(",") if part.strip())
    if not parts:
        raise ValueError(f"Invalid empty shape: {shape_text}")
    return parts


def parse_flat_field(field: str, dtype: np.dtype) -> np.ndarray:
    values = np.fromstring(field, sep=" ", dtype=dtype)
    if values.size == 0:
        raise ValueError("Found empty flattened data field")
    return values


def infer_shape(flat_len: int, explicit_shape: Optional[Tuple[int, ...]], defaults: Sequence[Tuple[int, ...]]) -> Tuple[int, ...]:
    if explicit_shape is not None:
        expected = int(np.prod(explicit_shape))
        if expected != flat_len:
            raise ValueError(
                f"Explicit shape {explicit_shape} expects {expected} values, but row has {flat_len}"
            )
        return explicit_shape

    for candidate in defaults:
        if int(np.prod(candidate)) == flat_len:
            return candidate

    root = int(np.sqrt(flat_len))
    if root * root == flat_len:
        return (root, root)

    raise ValueError(
        f"Could not infer shape for flattened length {flat_len}. Pass --pressure-shape/--depth-shape explicitly."
    )


def depth_to_colormap(depth_image: np.ndarray, max_depth_mm: int = 5000) -> np.ndarray:
    clipped = np.clip(depth_image, 0, max_depth_mm)
    normalized = cv2.normalize(clipped, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
    return cv2.applyColorMap(normalized, cv2.COLORMAP_TURBO)


def normalize_to_uint8(image: np.ndarray) -> np.ndarray:
    if image.dtype == np.uint8:
        return image
    return cv2.normalize(image, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)


def to_bgr_for_display(image: np.ndarray) -> np.ndarray:
    if image.ndim == 2:
        gray = normalize_to_uint8(image)
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

    if image.ndim != 3:
        raise ValueError(f"Unsupported frame ndim={image.ndim}; expected 2D or 3D")

    channels = image.shape[2]
    if channels == 4:
        rgba = normalize_to_uint8(image)
        return cv2.cvtColor(rgba, cv2.COLOR_BGRA2BGR)
    if channels == 3:
        return normalize_to_uint8(image)
    if channels == 1:
        gray = normalize_to_uint8(image[:, :, 0])
        return cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

    raise ValueError(f"Unsupported channel count {channels}; expected 1, 3, or 4")


def draw_text_block(frame: np.ndarray, lines: Iterable[str]) -> np.ndarray:
    output = frame.copy()
    lines = [line for line in lines if line]
    if not lines:
        return output

    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.75
    thickness = 2
    margin = 12
    line_gap = 8

    sizes = [cv2.getTextSize(line, font, font_scale, thickness)[0] for line in lines]
    width = max(s[0] for s in sizes)
    height = sum(s[1] for s in sizes) + line_gap * (len(lines) - 1)

    top_left = (margin, margin)
    bottom_right = (margin + width + 24, margin + height + 24)
    cv2.rectangle(output, top_left, bottom_right, (0, 0, 0), -1)
    cv2.rectangle(output, top_left, bottom_right, (255, 255, 255), 1)

    y = margin + 18
    for line, size in zip(lines, sizes):
        cv2.putText(output, line, (margin + 12, y), font, font_scale, (255, 255, 255), thickness, cv2.LINE_AA)
        y += size[1] + line_gap

    return output


def open_video_writer(path: Path, fps: float, frame_size: Tuple[int, int], codec: str) -> cv2.VideoWriter:
    fourcc = cv2.VideoWriter_fourcc(*codec)
    writer = cv2.VideoWriter(str(path), fourcc, fps, frame_size)
    if not writer.isOpened():
        raise RuntimeError(
            f"Failed to open video writer for {path}. Try a different codec with --codec (e.g. MJPG) or extension."
        )
    return writer


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert flattened CSV frames into a side-by-side pressure/depth video with timestamp overlay."
    )
    parser.add_argument("--input-csv", type=Path, required=True, help="Path to CSV generated by recorder")
    parser.add_argument("--output-video", type=Path, required=True, help="Output video path, e.g. output.mp4")
    parser.add_argument("--fps", type=float, default=15.0, help="Output video FPS")
    parser.add_argument("--codec", default="mp4v", help="OpenCV FOURCC codec (default: mp4v)")
    parser.add_argument(
        "--pressure-shape",
        type=parse_shape,
        default=None,
        help="Shape for pressure/rgb_data, e.g. 3072,4096,4",
    )
    parser.add_argument(
        "--depth-shape",
        type=parse_shape,
        default=None,
        help="Shape for depth_data, e.g. 512,512",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=0.25,
        help="Uniform scale for output frame dimensions (default: 0.25)",
    )
    parser.add_argument(
        "--max-frames",
        type=int,
        default=None,
        help="Optional maximum number of frames to render",
    )
    args = parser.parse_args()

    if args.scale <= 0:
        raise ValueError("--scale must be > 0")

    if not args.input_csv.exists():
        raise FileNotFoundError(f"Input CSV not found: {args.input_csv}")

    args.output_video.parent.mkdir(parents=True, exist_ok=True)

    writer: Optional[cv2.VideoWriter] = None
    frame_count = 0

    with args.input_csv.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        if reader.fieldnames is None:
            raise ValueError("CSV has no header row")

        pressure_col = "pressure_data" if "pressure_data" in reader.fieldnames else "rgb_data"
        if pressure_col not in reader.fieldnames:
            raise ValueError("CSV must contain either 'pressure_data' or 'rgb_data' column")
        if "depth_data" not in reader.fieldnames or "timestamp" not in reader.fieldnames:
            raise ValueError("CSV must contain 'timestamp' and 'depth_data' columns")

        inferred_pressure_shape: Optional[Tuple[int, ...]] = args.pressure_shape
        inferred_depth_shape: Optional[Tuple[int, ...]] = args.depth_shape

        for row_idx, row in enumerate(reader):
            if args.max_frames is not None and frame_count >= args.max_frames:
                break

            timestamp = row.get("timestamp", "")
            pressure_dtype = np.float32 if pressure_col == "pressure_data" else np.uint8
            pressure_flat = parse_flat_field(row[pressure_col], pressure_dtype)
            depth_flat = parse_flat_field(row["depth_data"], np.uint16)

            inferred_pressure_shape = infer_shape(
                pressure_flat.size,
                inferred_pressure_shape,
                defaults=(DEFAULT_RGB_SHAPE, (DEFAULT_RGB_SHAPE[0], DEFAULT_RGB_SHAPE[1], 3), DEFAULT_DEPTH_SHAPE),
            )
            inferred_depth_shape = infer_shape(
                depth_flat.size,
                inferred_depth_shape,
                defaults=(DEFAULT_DEPTH_SHAPE, DEFAULT_RGB_SHAPE[:2]),
            )

            pressure_frame = pressure_flat.reshape(inferred_pressure_shape)
            depth_frame = depth_flat.reshape(inferred_depth_shape)

            pressure_bgr = to_bgr_for_display(pressure_frame)
            depth_bgr = depth_to_colormap(depth_frame)

            target_height = max(pressure_bgr.shape[0], depth_bgr.shape[0])
            if pressure_bgr.shape[0] != target_height:
                target_width = int(round(pressure_bgr.shape[1] * target_height / pressure_bgr.shape[0]))
                pressure_bgr = cv2.resize(pressure_bgr, (target_width, target_height), interpolation=cv2.INTER_AREA)
            if depth_bgr.shape[0] != target_height:
                target_width = int(round(depth_bgr.shape[1] * target_height / depth_bgr.shape[0]))
                depth_bgr = cv2.resize(depth_bgr, (target_width, target_height), interpolation=cv2.INTER_NEAREST)

            combined = np.hstack([pressure_bgr, depth_bgr])
            if args.scale != 1.0:
                scaled_w = max(2, int(round(combined.shape[1] * args.scale)))
                scaled_h = max(2, int(round(combined.shape[0] * args.scale)))
                combined = cv2.resize(combined, (scaled_w, scaled_h), interpolation=cv2.INTER_AREA)

            overlay_lines = [
                f"frame={row_idx}",
                f"timestamp_ns={timestamp}",
                f"left={pressure_col}",
                "right=depth_data",
            ]
            combined = draw_text_block(combined, overlay_lines)

            if writer is None:
                writer = open_video_writer(
                    args.output_video,
                    fps=args.fps,
                    frame_size=(combined.shape[1], combined.shape[0]),
                    codec=args.codec,
                )

            writer.write(combined)
            frame_count += 1

    if writer is not None:
        writer.release()

    if frame_count == 0:
        raise RuntimeError("No frames were written. Check input CSV and --max-frames setting.")

    print(f"Wrote {frame_count} frames to {args.output_video}")


if __name__ == "__main__":
    main()
